{ pkgs, ... }: {
  # NOTE: (2020-03-12) use this instead of `programs.emacs.package = emacsEnv`
  # because the latter is not compatible with packages generated by
  # `emacsWithPackages`. See https://github.com/NixOS/nixpkgs/issues/66706
  home.packages = [ pkgs.emacsEnv ];

  home.file.".emacs.d" = {
    source = "${pkgs.mcwitt-dotfiles}/emacs.d/";
    recursive = true;
  };
}
